# Feature Engineering
The objective of this notebook is to create new features from the cleaned dataset that will improve business analysis and support machine learning models.

In [1]:
import pandas as pd
import numpy as np

In [2]:
clean_df = pd.read_csv("Retail_Cleaned.csv")

In [3]:
clean_df["InvoiceDate"] = pd.to_datetime(clean_df["InvoiceDate"])

In [4]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400916 entries, 0 to 400915
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      400916 non-null  int64
 1   StockCode    400916 non-null  str
 2   Description  400916 non-null  str
 3   Quantity     400916 non-null  int64
 4   InvoiceDate  400916 non-null  datetime64[us]
 5   Price        400916 non-null  float64
 6   Customer ID  400916 non-null  float64
 7   Country      400916 non-null  str
dtypes: datetime64[us](1), float64(2), int64(2), str(3)
memory usage: 41.8 MB

## Feature 1: TotalAmount

TotalAmount represents the revenue generated from each transaction.

Formula:
TotalAmount = Quantity × Price

In [5]:
clean_df["TotalAmount"] = clean_df["Quantity"] * clean_df["Price"]

In [6]:
clean_df[["Quantity","Price","TotalAmount"]].head()

   Quantity  Price  TotalAmount
0        12   6.95         83.4
1        12   6.75         81.0
2        12   6.75         81.0
3        48   2.10        100.8
4        24   1.25         30.0

## Feature 2: Year

In [7]:
clean_df["Year"] = clean_df["InvoiceDate"].dt.year

In [8]:
clean_df[["InvoiceDate","Year"]].head()

          InvoiceDate  Year
0 2009-12-01 07:45:00  2009
1 2009-12-01 07:45:00  2009
2 2009-12-01 07:45:00  2009
3 2009-12-01 07:45:00  2009
4 2009-12-01 07:45:00  2009

In [9]:
clean_df["Month"] = clean_df["InvoiceDate"].dt.month

In [10]:
clean_df[["InvoiceDate","Month"]].head()

          InvoiceDate  Month
0 2009-12-01 07:45:00     12
1 2009-12-01 07:45:00     12
2 2009-12-01 07:45:00     12
3 2009-12-01 07:45:00     12
4 2009-12-01 07:45:00     12

In [11]:
clean_df["MonthName"] = clean_df["InvoiceDate"].dt.month_name()

In [12]:
clean_df[["Month","MonthName"]].head()

   Month MonthName
0     12  December
1     12  December
2     12  December
3     12  December
4     12  December

In [13]:
clean_df["Day"] = clean_df["InvoiceDate"].dt.day

In [14]:
clean_df[["InvoiceDate","Day"]].head()

          InvoiceDate  Day
0 2009-12-01 07:45:00    1
1 2009-12-01 07:45:00    1
2 2009-12-01 07:45:00    1
3 2009-12-01 07:45:00    1
4 2009-12-01 07:45:00    1

In [15]:
clean_df["Weekday"] = clean_df["InvoiceDate"].dt.day_name()

In [16]:
clean_df[["InvoiceDate","Weekday"]].head()

          InvoiceDate  Weekday
0 2009-12-01 07:45:00  Tuesday
1 2009-12-01 07:45:00  Tuesday
2 2009-12-01 07:45:00  Tuesday
3 2009-12-01 07:45:00  Tuesday
4 2009-12-01 07:45:00  Tuesday

In [17]:
clean_df["Hour"] = clean_df["InvoiceDate"].dt.hour

In [18]:
clean_df[["InvoiceDate","Hour"]].head()

          InvoiceDate  Hour
0 2009-12-01 07:45:00     7
1 2009-12-01 07:45:00     7
2 2009-12-01 07:45:00     7
3 2009-12-01 07:45:00     7
4 2009-12-01 07:45:00     7

In [19]:
clean_df["Weekend"] = clean_df["Weekday"].isin(["Saturday","Sunday"])

In [20]:
clean_df["Weekend"] = clean_df["Weekend"].astype(int)

In [21]:
clean_df[["Weekday","Weekend"]].head()

   Weekday  Weekend
0  Tuesday        0
1  Tuesday        0
2  Tuesday        0
3  Tuesday        0
4  Tuesday        0

In [22]:
clean_df["Quarter"] = clean_df["InvoiceDate"].dt.quarter

In [23]:
clean_df[["InvoiceDate","Quarter"]].head()

          InvoiceDate  Quarter
0 2009-12-01 07:45:00        4
1 2009-12-01 07:45:00        4
2 2009-12-01 07:45:00        4
3 2009-12-01 07:45:00        4
4 2009-12-01 07:45:00        4

In [24]:
def time_period(hour):
    if hour < 12:
        return "Morning"
    elif hour < 17:
        return "Afternoon"
    else:
        return "Evening"

clean_df["TimeOfDay"] = clean_df["Hour"].apply(time_period)

In [25]:
clean_df[["Hour","TimeOfDay"]].head()

   Hour TimeOfDay
0     7   Morning
1     7   Morning
2     7   Morning
3     7   Morning
4     7   Morning

In [26]:
clean_df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalAmount,Year,Month,MonthName,Day,Weekday,Hour,Weekend,Quarter,TimeOfDay
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,December,1,Tuesday,7,0,4,Morning
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,December,1,Tuesday,7,0,4,Morning
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,December,1,Tuesday,7,0,4,Morning
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,December,1,Tuesday,7,0,4,Morning
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,December,1,Tuesday,7,0,4,Morning

In [27]:
clean_df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country', 'TotalAmount', 'Year', 'Month',
       'MonthName', 'Day', 'Weekday', 'Hour', 'Weekend', 'Quarter',
       'TimeOfDay'],
      dtype='str')

In [28]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400916 entries, 0 to 400915
Data columns (total 18 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      400916 non-null  int64
 1   StockCode    400916 non-null  str
 2   Description  400916 non-null  str
 3   Quantity     400916 non-null  int64
 4   InvoiceDate  400916 non-null  datetime64[us]
 5   Price        400916 non-null  float64
 6   Customer ID  400916 non-null  float64
 7   Country      400916 non-null  str
 8   TotalAmount  400916 non-null  float64
 9   Year         400916 non-null  int32
 10  Month        400916 non-null  int32
 11  MonthName    400916 non-null  str
 12  Day          400916 non-null  int32
 13  Weekday      400916 non-null  str
 14  Hour         400916 non-null  int32
 15  Weekend      400916 non-null  int64
 16  Quarter      400916 non-null  int32
 17  TimeOfDay    400916 non-null  str
dtypes: datetime64[us](1), float64(3), int32(5), int64(3), str(6)
memory usage: 73.0 MB

In [29]:
clean_df[
    ["TotalAmount","Year","Month","MonthName","Day",
     "Weekday","Hour","Weekend","Quarter","TimeOfDay"]
].head()

,TotalAmount,Year,Month,MonthName,Day,Weekday,Hour,Weekend,Quarter,TimeOfDay
0,83.4,2009,12,December,1,Tuesday,7,0,4,Morning
1,81.0,2009,12,December,1,Tuesday,7,0,4,Morning
2,81.0,2009,12,December,1,Tuesday,7,0,4,Morning
3,100.8,2009,12,December,1,Tuesday,7,0,4,Morning
4,30.0,2009,12,December,1,Tuesday,7,0,4,Morning

In [30]:
print(clean_df.shape)

(400916, 18)

In [31]:
clean_df.to_csv("Retail_Feature_Engineered.csv", index=False)

## Feature Engineering Summary

✔ Revenue Feature:
- TotalAmount

✔ Date Features:
- Year
- Month
- MonthName
- Day
- Weekday
- Quarter

✔ Time Features:
- Hour
- TimeOfDay
- Weekend

## Conclusion

The cleaned retail dataset was enhanced by creating new time-based and revenue-based features such as TotalAmount, Year, Month, MonthName, Day, Weekday, Hour, Weekend, Quarter, and TimeOfDay.

These engineered features will support Exploratory Data Analysis (EDA), customer behavior analysis, dashboard creation, and predictive modeling.